language:
  - python

python:
  - 3.8

install:
  - pip install coverage==4.5.4
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - py.test -vv exercises.py --cov exercises
  - coveralls

notifications:
  email: false
